services:
  robogait_gui:
    image: robogait_gui:humble
    network_mode: host
    ipc: host
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      QSG_RHI_BACKEND: opengl
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "${VIDEO_GID:-44}"
      - "${RENDER_GID:-110}"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.local/robogait:/home/robogait/.local/robogait:rw
    command: ros2 run robogait_gui robogait_gui
